# Generated by Django 4.1.1 on 2023-01-07 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='DueDate',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='paymentStatus',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='timeStamp',
        ),
    ]
