# Generated by Django 4.1.1 on 2023-01-19 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_attendance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='SelectMembershipplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.membershipplan'),
        ),
    ]
