# Generated by Django 4.1 on 2023-01-19 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_alter_enrollment_selectmembershipplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='TrainedBy',
            field=models.ForeignKey(default='Ex-employee', on_delete=django.db.models.deletion.SET_DEFAULT, to='authapp.trainer'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='SelectTrainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.trainer'),
        ),
    ]
