# Generated by Django 4.1 on 2023-01-19 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_alter_attendance_trainedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='TrainedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.trainer'),
        ),
    ]
